#!/usr/bin/env python3
"""Report missing castle data, stamp images and gosyuin images.

Usage: python3 scripts/audit_castle_data.py > docs/castle-data-gaps.md
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "JapanCastleBook/Castle Loader/Data/castles.json")
ASSETS = os.path.join(ROOT, "JapanCastleBookSwiftUI/Assets.xcassets")

# Fields the app displays (see CastleItemMapper), in priority order.
APP_FIELDS = [
    ("stamp_location", "stamp location"),
    ("access_guide", "access"),
    ("opening_hours", "hours"),
    ("phone_number", "phone"),
    ("image_urls", "photos"),
    ("related_websites", "websites"),
    ("parking_info", "parking"),
]


def imagesets(folder):
    path = os.path.join(ASSETS, folder)
    return {n[: -len(".imageset")] for n in os.listdir(path) if n.endswith(".imageset")}


def is_empty(value):
    return value in ("", [], None)


def main():
    castles = sorted(json.load(open(DATA)), key=lambda c: c["id"]["value"])
    stamps = imagesets("castle-stamps")
    gosyuin = imagesets("castle-gosyuin")
    linked_stamps = {c["stamp_image_name"] for c in castles if c.get("stamp_image_name")}

    print("# Castle data gaps\n")
    print("Generated by `scripts/audit_castle_data.py`.\n")

    unlinked = sorted(stamps - linked_stamps)
    if unlinked:
        print("## Stamp assets not linked in castles.json\n")
        print("These images exist in `castle-stamps` but no castle's `stamp_image_name` points to them:\n")
        for name in unlinked:
            print(f"- `{name}`")
        print()

    for title, lo, hi in [("Top 100 (1–100)", 1, 100), ("Next 100 (101–200)", 101, 200)]:
        series = [c for c in castles if lo <= c["id"]["value"] <= hi]
        print(f"## {title}\n")
        print("| # | Castle | Stamp | Gosyuin | Missing fields |")
        print("|---|---|---|---|---|")
        for c in series:
            stamp = c.get("stamp_image_name")
            stamp_cell = "✅" if stamp and stamp in stamps else "❌"
            gos_cell = "✅" if c.get("gosyuin_image_name") else "–"
            missing = [label for key, label in APP_FIELDS if is_empty(c.get(key))]
            if stamp_cell == "✅" and not missing:
                continue
            print(f"| {c['id']['value']} | {c['name']} | {stamp_cell} | {gos_cell} | {', '.join(missing)} |")
        print()


if __name__ == "__main__":
    main()
